{% set name = "filebutler" %}
{% set version = "0.25.0" %}
{% set sha256 = "9b351f430fc8f0ec6f63067a84d1886da82ae6cf7789a7d2c6458d12c1f80397" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/tesujimath/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [py2k or win]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - filebutler = filebutler.__main__:main

requirements:
  build:
    - python
    - setuptools
    - setuptools_scm
    - setuptools_scm_git_archive
    - future
    - pytz
    - tzlocal

  run:
    - python
    - future
    - pytz
    - setuptools
    - tzlocal

test:
  imports:
    - filebutler
  commands:
    - filebutler --help

about:
  home: https://github.com/tesujimath/{{ name }}
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Utility for managing old files in large directory structures'
  description: |
    Filebutler is a utility for managing old files in huge directory trees.
    Huge means of the order of 100 million files. The motivation is that
    find is far too slow on directory trees with this many files. Even
    working with filelists generated offline by find can be rather slow for
    interactive use. Filebutler improves on this by structuring filelists by
    age, by size, by owner, and by dataset.
  doc_url: http://{{ name }}.readthedocs.io/
  dev_url: https://github.com/tesujimath/{{ name }}

extra:
  recipe-maintainers:
    - tesujimath
