appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Y19meHNZtr3J3X1AihUvKm+LANW1dnONYkFk3L1fbNiMqs/uXh+IpHSLau8vUhMq8l3A7M1VbSVUxM9/Kep4IOiVLA4bKUkmcGDJgfWrf5rypQF0lyq+IvzFd8cNywx++lvUc6PuT/r2iB793NTYWFj0Y+UCERN3m2fPwipRwuyQDy4uAjaUig7cn5j4nFcqGi7kEeIawIwp/IzSke9+563mM0lSyJxZtVFyL6rcNBdqergPuyWJXoutpYPCao84DxJzVg0EMYZjvCoqdwAh0Cm4Q8xPL0pHCkqSdZ2411bs4a7suYrm6qwuXDIOXTKWlw13W7kro40LqN6e6atRZFmXBaPeWtIZMZFP3lLNboyY5j5VsT2PqHIU2swySDAp3r4EQj257PEcQkC7pdCYssiXAbqAVZ+y2nEUQljPDPo3fJUALnNDg0Io9a7fZf6x7C9qV5mF8wRc/xDZRnnMdaKgf93+KDJ5hVXP8q7fqk9JaPi0SPdR6Hj0TU9S7DEKgm7uOjQTgZG9cO5/SEMQvZ89+CfGMktjJk/xtBsa17V5ZguFE4FMlaOyryEybbJwNqoquVCngJcYl6yg6/+LPTEyh9GI9G8jBtbG/0jqq/XG5xPR3pj0a7oTZArLYp0QeYhjfdSufo/DnEYM6m8qLglyydIVqxOH4woEPASOJjw=}
conda_forge_output_validation: true
